services:
  nginx_fasm:
    image: nginx:1.24
    container_name: nginx_fasm
    volumes:
      # - ./ssl.crt:/etc/nginx/ssl.crt
      # - ./ssl.key:/etc/nginx/ssl.key
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - api_fasm
    networks:
      - net_fasm

  api_fasm:
    image: api_fasm:v0.1.0
    env_file:
      - .env
    ports:
      - 10080:80
    volumes:
      - ./logs/fasm:/fasm/logs
    networks:
      - net_fasm
      - net_db
    depends_on:
      - redis_fasm
      - pg_fasm

  redis_fasm:
    image: redis
    command:
      [
        "redis-server",
        "--port",
        "6379",
        "--cluster-enabled",
        "no",
        "--cluster-node-timeout",
        "5000",
        "--appendonly",
        "yes",
      ]
    networks:
      - net_db
    ports:
      - "16379:6379"

  pg_fasm:
    image: postgres:15.3-bullseye
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - net_db
    ports:
      - "15432:5432"

volumes:
  pgdata:

networks:
  net_fasm:
  net_db: